# Generated by Django 4.2.2 on 2023-07-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=2000)),
                ('education', models.CharField(max_length=200)),
                ('work_experience', models.TextField(max_length=2000)),
                ('projects', models.TextField(max_length=2000)),
                ('skills', models.TextField(max_length=2000)),
            ],
        ),
    ]
